data:
  img_dir: 'data/processed/patches'
  train_csv: 'data/processed/train.csv'
  val_csv: 'data/processed/val.csv'

model:
  type: 'resnet' # or 'vit'
  num_classes: 2
  vit_name: 'vit_base_patch16_224'
  
training:
  epochs: 10
  batch_size: 32
  lr: 3e-4
  outdir: 'experiments/logs'